"""empty message

Revision ID: 69aac42f6158
Revises: d589f29d9786
Create Date: 2022-06-28 15:34:34.946615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69aac42f6158'
down_revision = 'd589f29d9786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Personajes', sa.Column('color_cabello', sa.String(length=50), nullable=False))
    op.add_column('Personajes', sa.Column('altura', sa.Integer(), nullable=False))
    op.add_column('Planets', sa.Column('clima', sa.String(length=50), nullable=False))
    op.add_column('Planets', sa.Column('terreno', sa.String(length=250), nullable=False))
    op.add_column('Planets', sa.Column('rotación', sa.String(length=250), nullable=False))
    op.add_column('Planets', sa.Column('población', sa.String(length=250), nullable=False))
    op.add_column('Planets', sa.Column('periodo_orbital', sa.String(length=250), nullable=False))
    op.add_column('Planets', sa.Column('diametro', sa.String(length=250), nullable=False))
    op.drop_column('Planets', 'diameter')
    op.drop_column('Planets', 'climate')
    op.drop_column('Planets', 'terrain')
    op.drop_column('Planets', 'population')
    op.drop_column('Planets', 'orbital_Period')
    op.drop_column('Planets', 'rotation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Planets', sa.Column('rotation', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('Planets', sa.Column('orbital_Period', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('Planets', sa.Column('population', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('Planets', sa.Column('terrain', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('Planets', sa.Column('climate', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('Planets', sa.Column('diameter', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('Planets', 'diametro')
    op.drop_column('Planets', 'periodo_orbital')
    op.drop_column('Planets', 'población')
    op.drop_column('Planets', 'rotación')
    op.drop_column('Planets', 'terreno')
    op.drop_column('Planets', 'clima')
    op.drop_column('Personajes', 'altura')
    op.drop_column('Personajes', 'color_cabello')
    # ### end Alembic commands ###
