"""empty message

Revision ID: d589f29d9786
Revises: 031820bf5d46
Create Date: 2022-06-28 15:24:00.022746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd589f29d9786'
down_revision = '031820bf5d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_personaje', sa.String(length=100), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('color_ojos', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_personaje'),
    sa.UniqueConstraint('nombre_personaje')
    )
    op.drop_index('name', table_name='character')
    op.drop_index('name_2', table_name='character')
    op.drop_index('url_image', table_name='character')
    op.drop_index('url_image_2', table_name='character')
    op.drop_table('character')
    op.add_column('Planets', sa.Column('terrain', sa.String(length=250), nullable=False))
    op.add_column('Planets', sa.Column('rotation', sa.String(length=250), nullable=False))
    op.add_column('Planets', sa.Column('population', sa.String(length=250), nullable=False))
    op.add_column('Planets', sa.Column('orbital_Period', sa.String(length=250), nullable=False))
    op.add_column('Planets', sa.Column('diameter', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Planets', 'diameter')
    op.drop_column('Planets', 'orbital_Period')
    op.drop_column('Planets', 'population')
    op.drop_column('Planets', 'rotation')
    op.drop_column('Planets', 'terrain')
    op.create_table('character',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('birth_date', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hair_color', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('eye_color', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('skin_color', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('url_image', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('url_image_2', 'character', ['url_image'], unique=False)
    op.create_index('url_image', 'character', ['url_image'], unique=False)
    op.create_index('name_2', 'character', ['name'], unique=False)
    op.create_index('name', 'character', ['name'], unique=False)
    op.drop_table('Personajes')
    # ### end Alembic commands ###
