"""empty message

Revision ID: ed91da981868
Revises: 69aac42f6158
Create Date: 2022-06-28 17:23:56.808023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed91da981868'
down_revision = '69aac42f6158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nombre', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['nombre'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'nombre')
    # ### end Alembic commands ###
